# Generated by Django 4.2.21 on 2025-10-20 21:46

import clickhouse_backend.models
import clickhouse_search.backend.fields
from django.db import migrations, models, connections
import django.db.models.manager
from string import Template

from settings import DATABASES

def add_affected_status_orderby(reference_genome: str, dataset_type: str):
    def inner(apps, schema_editor):
        reference = f"{reference_genome}/{dataset_type}"
        old_tbl = f"{reference}/project_gt_stats"
        tmp_tbl = f"{reference}/project_gt_stats_new_order_by"
        with connections['clickhouse_write'].cursor() as cursor:
            # 1. Get the current DDL
            cursor.execute(
                f"SELECT create_table_query FROM system.tables WHERE table = '{old_tbl}' AND database = '{DATABASES['default']['NAME']}'"
            )
            ddl = cursor.fetchone()[0]
            if "ORDER BY (project_guid, key, sample_type)" in ddl:
                old_order_by = "ORDER BY (project_guid, key, sample_type)"
                new_order_by = "ORDER BY (project_guid, key, sample_type, affected)"
            elif "ORDER BY (project_guid, key)" in ddl:
                old_order_by = "ORDER BY (project_guid, key)"
                new_order_by = "ORDER BY (project_guid, key, affected)"
            ddl = ddl.replace(
                old_order_by,
                new_order_by,
            )
            ddl = ddl.replace(f"CREATE TABLE {DATABASES['default']['NAME']}.`{old_tbl}`", f"CREATE TABLE {DATABASES['default']['NAME']}.`{tmp_tbl}`")
            cursor.execute(ddl)
            cursor.execute(
                f"INSERT INTO `{tmp_tbl}` SELECT * FROM `{old_tbl}`"
            )
            cursor.execute(
                f"EXCHANGE TABLES `{tmp_tbl}` AND `{old_tbl}`"
            )
            cursor.execute(
                f"DROP TABLE `{tmp_tbl}`"
            )
    return inner

class Migration(migrations.Migration):
    dependencies = [
        ("clickhouse_search", "0020_clinvar_new_reference_data"),
    ]

    operations = [
        migrations.RunPython(
            add_affected_status_orderby(
                reference_genome="GRCh37",
                dataset_type="SNV_INDEL",
            ), 
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            add_affected_status_orderby(
                reference_genome="GRCh38",
                dataset_type="SNV_INDEL",
            ), 
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            add_affected_status_orderby(
                reference_genome="GRCh38",
                dataset_type="MITO",
            ), 
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            add_affected_status_orderby(
                reference_genome="GRCh38",
                dataset_type="SV",
            ), 
            reverse_code=migrations.RunPython.noop
        ),
    ]
